# Generated by Django 4.2.4 on 2023-11-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_alter_savingproducts_mtrt_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingoptions',
            name='fin_prdt_cd',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='max_limit',
            field=models.IntegerField(null=True),
        ),
    ]
